/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestor.vistas;

import com.gestor.daos.DelitoDAO;
import com.gestor.daos.PersonaDAO;
import com.gestor.impl.DelitoImpl;
import com.gestor.impl.PersonaImpl;
import com.gestor.modelo.Delito;
import com.gestor.modelo.Persona;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Luis
 */
public class VistaExpediente extends javax.swing.JInternalFrame {

    PersonaDAO personaService;
    DelitoDAO delitoService;

    public VistaExpediente() {
        initComponents();
        setClosable(true);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        llenarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        comboDelito = new javax.swing.JComboBox();
        lblDelito = new javax.swing.JLabel();
        lblPersona = new javax.swing.JLabel();
        comboPersona = new javax.swing.JComboBox();
        lblFechaDelito = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblCartelDescripcion = new javax.swing.JLabel();
        btnGenerarExpediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionDenuncia = new javax.swing.JTextArea();
        txtFechaDelito = new com.toedter.calendar.JDateChooser();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("GENERAR NUEVO EXPEDIENTE");

        comboDelito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDelitoActionPerformed(evt);
            }
        });

        lblDelito.setText("SELECCIONE DELITO");

        lblPersona.setText("SELECCIONE PERSONA");

        comboPersona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFechaDelito.setText("FECHA DELITO");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/balanza1.png"))); // NOI18N
        lblIcono.setText("jLabel2");

        lblCartelDescripcion.setText("INGRESE LA DESCRIPCIÓN DE LOS HECHOS");

        btnGenerarExpediente.setText("GENERAR EXPEDIENTE");
        btnGenerarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarExpedienteActionPerformed(evt);
            }
        });

        txtDescripcionDenuncia.setColumns(20);
        txtDescripcionDenuncia.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionDenuncia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGenerarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCartelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(comboDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFechaDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblFechaDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDelito)
                    .addComponent(lblPersona)
                    .addComponent(lblFechaDelito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(lblCartelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnGenerarExpediente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechaDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDelitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDelitoActionPerformed

    private void btnGenerarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarExpedienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnGenerarExpediente;
    public static javax.swing.JComboBox comboDelito;
    public static javax.swing.JComboBox comboPersona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCartelDescripcion;
    private javax.swing.JLabel lblDelito;
    private javax.swing.JLabel lblFechaDelito;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblPersona;
    public static javax.swing.JTextArea txtDescripcionDenuncia;
    public static com.toedter.calendar.JDateChooser txtFechaDelito;
    // End of variables declaration//GEN-END:variables

    private void llenarCombos() {

        List<String> listaDelitos = obtenerListaDelitos();
        List<String> listaPersonas = obtenerListaNombresPersonas();
        DefaultComboBoxModel modeloDelitos = new DefaultComboBoxModel(listaDelitos.toArray());
        DefaultComboBoxModel modeloPersonas = new DefaultComboBoxModel(listaPersonas.toArray());
        comboPersona.setModel(modeloPersonas);
        comboDelito.setModel(modeloDelitos);

    }

    private List<String> obtenerListaNombresPersonas() {
        personaService = new PersonaImpl();
        List<Persona> personas = personaService.listar();
        List<String> listaNombres = new ArrayList<String>();
        for (Persona listaPersonas : personas) {
            listaNombres.add(listaPersonas.getNombre() + " " + listaPersonas.getApellido() + " ("+listaPersonas.getDni()+")");
        }
        return listaNombres;
    }

    private List<String> obtenerListaDelitos() {
        delitoService = new DelitoImpl();
        List<Delito> delitos = delitoService.listarDelitos();
        List<String> listaDelitos = new ArrayList<String>();
        for (Delito delito : delitos) {
            listaDelitos.add(delito.getCaratula() + " ("+delito.getCodDelito()+")");
        }
        return listaDelitos;
    }

}
